# Generated by Django 2.0 on 2020-02-28 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='line1attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='line2attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='line3attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='line4attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='line5attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='operator_skill_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('grade', models.CharField(default='', max_length=1)),
                ('skill_percentage', models.CharField(default='', max_length=3)),
                ('operation', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('operation', models.CharField(default='', max_length=100)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('stop_time', models.CharField(default='', max_length=50)),
                ('duration', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('machine_stop_time', models.CharField(default='', max_length=50)),
                ('machine_run_time', models.CharField(default='', max_length=50)),
                ('machine_breakdown_time', models.CharField(default='', max_length=50)),
                ('frequency_of_machine_stop', models.IntegerField(default=0)),
                ('ticket_no_start', models.IntegerField(default=0)),
                ('ticket_no_end', models.IntegerField(default=0)),
                ('total_pieces', models.IntegerField(default=0)),
                ('ticket_no_run_time', models.IntegerField(default=0)),
                ('next_ticket_no_time', models.IntegerField(default=0)),
                ('ct', models.CharField(default='', max_length=50)),
                ('total_stitched_pieces', models.IntegerField(default=0)),
                ('rework_ticket_no', models.IntegerField(default=0)),
                ('rework_pieces', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('operator_name', models.CharField(default='', max_length=50)),
                ('operator_id', models.CharField(default='', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('line_no', models.CharField(default='', max_length=5)),
                ('address', models.CharField(default='', max_length=100)),
                ('product_category', models.CharField(default='', max_length=100)),
                ('product_sub_category', models.CharField(default='', max_length=100)),
                ('operation', models.CharField(default='', max_length=100)),
                ('operation_complexity', models.CharField(default='', max_length=100)),
                ('no_of_operation', models.CharField(default='', max_length=100)),
                ('skill_percentage', models.CharField(default='', max_length=3)),
                ('grade', models.CharField(default='', max_length=1)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
