# Generated by Django 2.0 on 2020-03-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorwindow',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='next_ticket_no_time',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='ticket_no_run_time',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='total_stitched_pieces',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='skill_percentage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
