# Generated by Django 2.0 on 2020-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_auto_20200304_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='line1attendence',
            name='product',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='line2attendence',
            name='product',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='line3attendence',
            name='product',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='line4attendence',
            name='product',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='line5attendence',
            name='product',
            field=models.CharField(default='', max_length=50),
        ),
    ]
