# Generated by Django 2.0 on 2020-03-09 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_auto_20200307_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaveCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('leave_start', models.DateField(default='', max_length=50)),
                ('leave_end', models.DateField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='line1attendence',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='line1attendence',
            name='leave_end',
        ),
        migrations.RemoveField(
            model_name='line1attendence',
            name='leave_start',
        ),
        migrations.RemoveField(
            model_name='line2attendence',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='line2attendence',
            name='leave_end',
        ),
        migrations.RemoveField(
            model_name='line2attendence',
            name='leave_start',
        ),
        migrations.RemoveField(
            model_name='line3attendence',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='line3attendence',
            name='leave_end',
        ),
        migrations.RemoveField(
            model_name='line3attendence',
            name='leave_start',
        ),
        migrations.RemoveField(
            model_name='line4attendence',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='line4attendence',
            name='leave_end',
        ),
        migrations.RemoveField(
            model_name='line4attendence',
            name='leave_start',
        ),
        migrations.RemoveField(
            model_name='line5attendence',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='line5attendence',
            name='leave_end',
        ),
        migrations.RemoveField(
            model_name='line5attendence',
            name='leave_start',
        ),
    ]
