# Generated by Django 2.0 on 2020-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_auto_20200309_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecalender',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
