# Generated by Django 2.0 on 2020-03-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_leavecalender_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator_skill_matrix',
            name='line_no',
            field=models.CharField(default='', max_length=5),
        ),
    ]
