# Generated by Django 2.0 on 2020-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_operator_skill_matrix_line_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator_skill_matrix',
            name='product_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
