# Generated by Django 2.0 on 2020-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0009_operator_skill_matrix_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorwindow',
            name='daily_achieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='daily_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='efficiency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='performance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='wip',
            field=models.IntegerField(default=0),
        ),
    ]
