# Generated by Django 2.0 on 2020-03-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0010_auto_20200317_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorwindow',
            name='next_operation',
            field=models.IntegerField(default=0),
        ),
    ]
