# Generated by Django 2.0 on 2020-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0011_operatorwindow_next_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorwindow',
            name='cutdefect_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='cutmiss_tkt_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='daily_cutting_miss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='finishreturn_tkt_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='repair_tkt_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operatorwindow',
            name='rework_ticket_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
