# Generated by Django 2.0 on 2020-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0013_auto_20200322_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorwindow',
            name='delaystart',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='demo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='fullswing',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='learing',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='machineissue',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='others',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='qualityissue',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='trimsissue',
            field=models.CharField(default='', max_length=50),
        ),
    ]
