# Generated by Django 2.0 on 2020-03-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0014_auto_20200323_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorwindow',
            name='delaystart',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='demo',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='fullswing',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='learing',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='machineissue',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='others',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='qualityissue',
        ),
        migrations.RemoveField(
            model_name='operatorwindow',
            name='trimsissue',
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='smed_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='smed_start_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='smed_stop_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operatorwindow',
            name='smed_value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
