# Generated by Django 2.0 on 2020-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0015_auto_20200323_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorwindow',
            name='maintenance_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operatorwindow',
            name='smed_value',
            field=models.IntegerField(default=0),
        ),
    ]
