# Generated by Django 3.0.3 on 2020-02-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='grade',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='no_of_operation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='operation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='operation_complexity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='operator_id',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='operator_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='product_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='product_sub_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='skill_percentage',
            field=models.CharField(default='', max_length=3),
        ),
    ]
