# Generated by Django 3.0.3 on 2020-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_operatorwindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorwindow',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorwindow',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorwindow',
            name='start_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorwindow',
            name='stop_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
