# Generated by Django 3.0.3 on 2020-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20200211_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorwindow',
            name='machine_breakdown_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorwindow',
            name='machine_run_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorwindow',
            name='machine_stop_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
