# Generated by Django 3.0.3 on 2020-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20200211_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator_skill_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('grade', models.CharField(default='', max_length=1)),
                ('skill_percentage', models.CharField(default='', max_length=3)),
                ('operation', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
