# Generated by Django 2.0 on 2020-02-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_auto_20200219_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='operator_id',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
