# Generated by Django 2.0 on 2020-02-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_auto_20200219_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='line_no',
            field=models.CharField(default='', max_length=5),
        ),
    ]
