# Generated by Django 2.0 on 2020-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator_attendence',
            name='leave',
            field=models.CharField(default='work', max_length=50),
        ),
        migrations.AddField(
            model_name='operator_attendence',
            name='leave_end',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operator_attendence',
            name='leave_start',
            field=models.CharField(default='', max_length=50),
        ),
    ]
