# Generated by Django 2.0 on 2020-02-27 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20200217_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='line2attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='line3attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='line4attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='line5attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(default='', max_length=5)),
                ('operator_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendence', models.CharField(default='', max_length=50)),
                ('leave_start', models.CharField(default='', max_length=50)),
                ('leave_end', models.CharField(default='', max_length=50)),
                ('leave', models.CharField(default='work', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='operator_attendence',
            new_name='line1attendence',
        ),
    ]
